slider = SHADOW_BIAS SHADOW_DISTORT_FACTOR SHADOW_BRIGHTNESS shadowMapResolution BLUE_AMOUNT GREEN_AMOUNT TERRAIN_GREY_AMOUNT TORCH_R TORCH_G TORCH_B FOG_START FOG_END FOG_MAX BORDER_FOG_START
 
screen = [Colors] [Lighting] [Fog] WAVING_PLANTS

screen.Colors = BLUE_AMOUNT GREEN_AMOUNT BLACK_SKY RED_SUN YELLOW_CLOUDS RED_ENTITIES TERRAIN_GREY_AMOUNT

screen.Lighting = LIGHTING_STYLE TORCH_R TORCH_G TORCH_B

screen.Fog = FOG_START FOG_END FOG_MAX BORDER_FOG_START